### ISSUE TITLE
Is property PROPERTY_NAME_GAZEMODE still useful ?

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#102]
Need to check that point discussing with some people.

**Comment by WaffleBuffer** [comment]
up

**Comment by kuhlkrein** [comment]
The only occurences of PROPERTY_NAME_GAZEMODE, DEFAULT_VALUE_GAZEMODE and gazeModeProperty are in the Configuration.java class and are not usefull to any other part of the code, so I think the answer is no. I'm removing it
