### ISSUE TITLE
Problem upgrading version

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#109]
@YannRobert Travis is ok and maven works on my computer. But I think, I made an error (I think I have mistaken released version and development version) and I don't see how to manage that. Can you check if it is ok ? 

Thank you !

**Comment by schwabdidier** [comment]
I don't planify to work on GazePlay next days if I don't have reported bug but my idea was to upgrade version as I published a release last Sunday.

**Comment by YannRobert** [comment]
Hi @schwabdidier 

I am not sure what you mean.
I see the last commit  (54afd0c) changes the version in POMs to a non-snapshot.
But there is no release, no tag. Also the commit message is customized, not generated by maven release.

Did you use the maven release or did you edit manually?
Anyway, you can revert the commit.

```
git revert 54afd0c
git push
```

Then you can restart your release process. (make sure to use mvn release as described in [BUILD.MD](https://github.com/schwabdidier/GazePlay/blob/master/BUILD.MD#how-to-release-the-software-for-version-tagging-in-official-scm-and-binaries-distribution))
