### ISSUE TITLE
#WhereIsIt sound effect repeat issue

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#110]
In ```where is the animal``` 

I get the voice question "where is the ... ?" twice, sometimes more, at the beginning of each game round, starting at the beginning of the second round.
The first round, I never have the question repeated twice.

Sometimes, it seems it collide with the "bravo" voice sound. 
Moreover, the "bravo" icon also sometimes blink rapidly.

After a few rounds (on round 3 or 4), the game start being very slow, the progress circle is filling up really slowly.

Reproducible : always
Environment : playing on Linux with the mouse

**Comment by schwabdidier** [comment]
oh ? Odd, I don't see that at all on Windows and MacOs.

**Comment by YannRobert** [comment]
fixed by #121 and #126
