### ISSUE TITLE
Sound effects alignment level

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#112]
There may be an issue with sound effect volume alignment.

It seems the bravo sound effect is rather loud, compared to the "where is the animal" questions sound effects.
So I am constantly trying to adjust the computer volume in vain.

**Comment by schwabdidier** [comment]
I don't know how to manage sound level in Java, it is very basic now :only things I found on the Web (as applauses) or I have generated with Amazon Web Services.

**Comment by schwabdidier** [comment]
I guess you fixed it
