### ISSUE TITLE
In "where is it", print the question on screen

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#113]
In games "where is it"
The question is currently only asked using a sound effect.

I think it would be great to have the question printed on screen too.
The question should remain on screen for the whole duration of the round.

Because sometimes, you didn't understand/hear the question sound effect, or you may have forgotten the question, so you really can't figure out what to do, and just randomly pick any option until you find the correct answer.

The printed question would be useful for the child parent to repeat the question slowly.

Maybe, in some cases, the sound effect is just annoying to hear, so you prefer to just rely on the message on screen, and turn off the volume.

**Comment by schwabdidier** [comment]
What do you think about what I did ? It is before the game. I don't see where it could be with all photos. It was not so difficult thank to your refactoring.

Now, length is 2000 ms, certainly it can configured.

**Comment by YannRobert** [comment]
Hi Didier. 
I just tried the game with the change.

So you introduced a black screen at the beginning of each round, printing the question, then disappearing before the multiple images are displayed.

That was not really what I had in mind. 
But it is not bad. It's may be better than what I had in mind actually, or not, I'm not sure.

What I had in mind was having the question printed on screen for the whole duration of the round.
Kind of like, you know, subtitles in the movies. The question is printed at the bottom of the screen. 
Maybe on a black stripe. Not over the images.

Anyways, I noticed a few issues / bugs when playing with the game since your change.
Now the animation timing is now behaving as expected. Their is a shift between the sound and the animation. Sometimes the next round starts playing before the bravo animation is completed.

**Comment by schwabdidier** [comment]
I wonder if there won't be too much information at the same time if we put both sentence and picture. It could be another option.

I don't have the bug you mention.

**Comment by YannRobert** [comment]
> I don't have the bug you mention.
I fixed it in #138

**Comment by YannRobert** [comment]
> I wonder if there won't be too much information at the same time if we put both sentence and picture. It could be another option.

I like it the way you did it. 
Yes, the game being gaze oriented, the whole point is to avoid displaying to much things on screen.

**Comment by schwabdidier** [comment]
So, we can close this issue. We will open new ones for improvements
