### ISSUE TITLE
Clear is not well done

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#132]
With eye-tracker (Tobii at least but I guess all eye-trackers), Node a still on the screen. We don't see them but events are still fired. 

For instance, I heard several times cream pie sound while on the home screen and then cream pie sound when I was playing Ninja.

**Comment by schwabdidier** [comment]
I experimented lot of problems trying to remove Nodes with eye-tracker. That is certainly why "root.getChildren().clear();" doesn't work.

**Comment by YannRobert** [comment]
Then we should restore the previous way of removing nodes. I won't be able to to it soon, so go on if you will.

I thought of an alternative way to switch from the menu to the game. You should not reuse the same scene object. 

You should create a new Scene object for the game, prepare it, then when ready, remove the game menu scene from the pane, add the game scene.
When the game ends. Just remove the game scene. And set back the game menu scene.
This way it's much easier to clean everything without risking to forget any objet and get memory leak. It's also a better separation between the menu and each game. The game does not need to know anything about the menu.

**Comment by schwabdidier** [comment]
You are right, it should be better

**Comment by schwabdidier** [comment]
BTW, it is a memory leaks, I have to investigate (again...) the problem

**Comment by schwabdidier** [comment]
I rewrote the function in order to help future debug (see issue #135)
