### ISSUE TITLE
A game, a scene

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#134]
As mentioned by @YannRobert in issue #132 :

> You should create a new Scene object for the game, prepare it, then when ready, remove the game menu scene from the pane, add the game scene.
When the game ends. Just remove the game scene. And set back the game menu scene.
This way it's much easier to clean everything without risking to forget any objet and get memory leak. It's also a better separation between the menu and each game. The game does not need to know anything about the menu.

**Comment by schwabdidier** [comment]
Maybe A game, a root would be better

**Comment by schwabdidier** [comment]
I was not able to do it this morning (always get a black screen when I tried to change root).

**Comment by YannRobert** [comment]
Hi didier, I started a refactoring to do this. Will provide a pull request shortly.
