### ISSUE TITLE
Full screen should be an option

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#141]
@YannRobert wrote : fullscreen seem to be very slow

I don't have this feeling (but my screens are not so big), so it can be an option

**Comment by schwabdidier** [comment]
@YannRobert : I don't find why it is full screen, then goes non full screen one second at the beginning of a game (I find where we disable full screen, then it goes back to full screen (because I ask it).

**Comment by YannRobert** [comment]
I also see the game appears to blink, going from fullscreen to windows mode then fullscreen.

I understand when it set a Scene into the Stage, that makes the stage exit fullscreen.

https://github.com/schwabdidier/GazePlay/blob/00434eb2db34aaa2e1f118012b2206870ddc4003/gazeplay/src/main/java/net/gazeplay/GraphicalContext.java#L30-L31

Maybe we can try to keep the same Scene, and just switch the root inside?

**Comment by YannRobert** [comment]
I think we can close this when #183 is merged
Remaining task is reported as #184
