### ISSUE TITLE
UX : accidental push on the exit button

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#148]
this is a UX issue

when exiting a game, you push the home button.
then it show the stats screen
to exit the stats screen, you push the home button,
then it show the home screen

right at the same position of the home button, 
in the home screen, there is the exit button

It you click multiple times the home button, you may accidentally exit the application,
especially when the home button is not responding very quickly, you tend to click multiple times.

**Comment by schwabdidier** [comment]
It is true. Two possibilities :
- a window to ask if the user wants to go out (but if one day we want to add eye tracker interaction with it it won't work;
- enable button click only after X seconds after display (X = 1 should be enough)

**Comment by YannRobert** [comment]
> a window to ask if the user wants to go out (but if one day we want to add eye tracker interaction with it it won't work;

a common solution, sounds acceptable
IMO I find this kind of confirm popups annoying

> enable button click only after X seconds after display (X = 1 should be enough)

I thought about it, but it sounds tricky, and arbitrary delay will not fit everyone
and user may experience that his legitimate click (when he really wants to exit quickly) is being ignored

I think it would be simpler and more effective to just relocate the exit button somewhere else on the screen. Like, at the top left of the home screen?

**Comment by schwabdidier** [comment]
Top left is the best solution, I agree

**Comment by schwabdidier** [comment]
Top left is the best solution, I agree

**Comment by schwabdidier** [comment]
@YannRobert I find top right better
