### ISSUE TITLE
Home button is too low in configuration and statistics

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#149]

**Comment by schwabdidier** [comment]
It is still the same for me.

**Comment by YannRobert** [comment]
Yes, you're right, I fixed it initially only for the home screen, but not for configuration and statistics

Please see PR #157 to fix the remaining

**Comment by schwabdidier** [comment]
Problem was coming from line grid.setPadding(new Insets(50, 50, 50, 50));
