### ISSUE TITLE
Magic cards : 2X2 is too much on the left

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#150]

**Comment by YannRobert** [comment]
I had to take a screenshot and count pixels on each side to see it.

**Comment by schwabdidier** [comment]
I don't understand, for me, it was on the left left  and now, it is ok. Maybe you fixed it in the previous pull ?

**Comment by YannRobert** [comment]
I meant you are right, is it also a bit more on the left for me, but just by less than 20 pixels, so it's hard to notice.

> Maybe you fixed it in the previous pull ?

I don't think so
