### ISSUE TITLE
Not easy to click home button when full screen in where is it games

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#153]

**Comment by YannRobert** [comment]
please provide more info

**Comment by schwabdidier** [comment]
Sorry, you are right. It is only in where is it games. I can only click on the 20% bottom part of the button else button disappear.

**Comment by YannRobert** [comment]
Oh, you mean "when you exit fullscreen, the application goes in window mode, the control panel layout is not resized, so the home button is displayed partially outside of the screen"

I see this too.
Didn't managed to fix this for the moment.

**Comment by WaffleBuffer** [comment]
I managed to fix this issue. For now it's on my forked project on the master branch : 
https://github.com/WaffleBuffer/GazePlay
At the end of the morning, i'll make a pull request.

**Comment by YannRobert** [comment]
@WaffleBuffer good

just remember to only fix 1 issue per commit
do not work on multiple subjects in the same branch

**Comment by WaffleBuffer** [comment]
Yes, i just realized i forget to commit the last fix. I'll do it next time and since this commit is just one line fix, i think it will be ok. Also, is that "good" to make some other tiny fix (like adding some @annotations) on the same commit or should i make a different commit ?

**Comment by schwabdidier** [comment]
gg @WaffleBuffer
