### ISSUE TITLE
home button doesn't work before first shoot

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#156]
at least for cream pie

**Comment by YannRobert** [comment]
I can't reproduce

**Comment by schwabdidier** [comment]
As long as home button is displayed, I can't click it. If I shoot or if the button disappear and appear again, I can click.

**Comment by WaffleBuffer** [comment]
Is this issue still up ? Because i can't reproduce the bug either.

**Comment by YannRobert** [comment]
If I remember correctly I managed to reproduce on Windows, but not on Linux.

**Comment by schwabdidier** [comment]
I still have the bug on my laptop with mac OS

**Comment by YannRobert** [comment]
Yes, I can still reproduce on Windows

**Comment by YannRobert** [comment]
fixed in 1.2
