### ISSUE TITLE
Check last commit

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#159]
@YannRobert This afternoon, we integrated @coylz 's project https://github.com/coylz/TobiiStreamEngineForJava

We don't need to manage that in GazePlay and many people would certainly like to use it for their Java project.

In GazePlay, we add that as Maven dependency. We think we manage that well but we would like that you check it. Especially as you have now a 4C, you can certainly try last version of distribution file to check it works. I will also try tomorrow at home.

Thanks in advance,

**Comment by YannRobert** [comment]
Yes, I saw the change, this is a good thing to externalize the dll in a separate project.

I tested the game with Tobii 4C, and found as issue. 
Please see issue  #161
