### ISSUE TITLE
Version 1.2 Release

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#160]
We expect to release Version 1.1.1 very soon. It could be very soon when strong bugs are fixed before the end of the week end. Game contributors may feel free to complete/modify.

Release note :
- Separate the Control Panel from the Game Panel (main contributor : @YannRobert)
- Play in Windowed mode (main contributor : @YannRobert)
- Where is it games have been improved (main contributor : @schwabdidier)
    - question in now written 
    - Pictograms can be introduced in customized game
    - Question length is configurable
- Tobii 4C and EyeX (main contributor : @coylz)
    - Use last version of Tobii's drivers
    - Dll are now directly in the jar

**Comment by YannRobert** [comment]
see milestone https://github.com/schwabdidier/GazePlay/milestones/Release%201.1.1

**Comment by YannRobert** [comment]
@schwabdidier this is a big release, we should skip ```1.1.1``` and go directly to ```1.2```

**Comment by YannRobert** [comment]
If every pending bug reports are fixed, maybe it is a good time to release?

**Comment by schwabdidier** [comment]
We still have the dll problem, isn't it ? @coylz will be back on Thursday to work on that. We can wait 2 days more no ? I am agree to go to 1.2

**Comment by schwabdidier** [comment]
So, tomorrow, we will release version 1.2 when I am sure tobii works.
