### ISSUE TITLE
When in window mode (not fullscreen), the gaze position is incorrect

### ISSUE THREAD

**Issue by coylz** [schwabdidier/GazePlay#164]
When we get the gaze position (from Tobii, EyeTribe...), the position is relative to the screen. If the application is in window mode, this position is incorrect because it is not relative to the window.

Possible solution:
substract the window position to the returned gaze position

**Comment by schwabdidier** [comment]
I confirm, it is a STRONG bug

**Comment by YannRobert** [comment]
Somebody confirms this is fixed ?
