### ISSUE TITLE
ScrathCards and transparent images

### ISSUE THREAD

**Issue by DMyTryC** [schwabdidier/GazePlay#165]
The transparent images that are used in this game don't count as finished when the image is revealed since some pixels to reveal remain in the unseen side of the image. This means that you cannot finish an image unless you look everywhere randomly.

**Comment by schwabdidier** [comment]
We should change images to 16:9 or 3:4 free images to avoid that kind of problem (following the screen).

**Comment by schwabdidier** [comment]
The problem comes from the black on the left and the right of a 3:4 image on a 16:9 screen. There is no way to distinguish the part to reveal.

**Comment by WaffleBuffer** [comment]
An idea to fix this issue would be to change the color of the part to "scratched" so it has not the same color as the background

**Comment by WaffleBuffer** [comment]
This appears to have been fixed by lowering the percentage of image to discover to win.
