### ISSUE TITLE
Fullscreen after game

### ISSUE THREAD

**Issue by DMyTryC** [schwabdidier/GazePlay#166]
The GazePlay app should go into fullscreen mode after a game ends, even if it is in windowed mode when the game ends.

**Comment by YannRobert** [comment]
Hi @DMyTryC 

I personally disagree with this user story.

I like to play in window mode, and don't want to exit fullscreen every time I start a new game.

Generally, we should respect the user's choice to exit fullscreen (or his choice to enter fullscreen).
If he wan't to toggle to fullscreen again, then it is his choice to make, and require his explicit action.

Maybe you want to add a button to toggle fullscreen in the main menu?

**Comment by WaffleBuffer** [comment]
Another problem raised is that eye tracking works better in fullscreen. So a proposition made is to force fullscreen since game launched (in the same way that a video game launched). I don't know if some tests have been done to know if eye tracking works great in windowed mode.
