### ISSUE TITLE
Game idea : Cups and Balls

### ISSUE THREAD

**Issue by DMyTryC** [schwabdidier/GazePlay#170]
I am proposing a game to be developed. The game principle is that there are multiple cups shown on the screen. One of the cups is opened and a ball is shown under it. After this, the cups are shown being shuffled and, when they stop being shuffled, the user chooses a cup. The cup is opened. If the user didn't find the ball, the cup disappears and he gets another chance to find the ball, all up to the point of him finding the ball. 

Possible settings for the game would be :
- The ball size, color
- The speed at which the cups are shuffled at

**Comment by schwabdidier** [comment]
The number of cups can be a setting too
