### ISSUE TITLE
When in fullscreen, and the application change screen, fullscreen goes off then on

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#184]
As reported in https://github.com/schwabdidier/GazePlay/issues/141#issuecomment-355950870

and rephrased here https://github.com/schwabdidier/GazePlay/issues/141#issuecomment-356106375

the fullscreen app appears to blink when changing Scene.

There is a technical explaination for that, and probably a design hack we can use to avoid it.

**Comment by WaffleBuffer** [comment]
Is this issue still opened ?

**Comment by kuhlkrein** [comment]
Yes @WaffleBuffer, should be still opened. You don't have this problem on your project ?

**Comment by WaffleBuffer** [comment]
I think i do but the blinking is really fast but we can try to fix it anyway.

**Comment by WaffleBuffer** [comment]
I am currently working on version with the solution suggested in [ #141 (comment)](https://github.com/schwabdidier/GazePlay/issues/141#issuecomment-356106375). It solves the blinking issue but i need to rework all around a bit to adapt everything to the new solution.
Also is there a way to signal that i a currently working on this issue ?

**Comment by WaffleBuffer** [comment]
For the first point i jut signaled that i was working on this issue.
On the second point i wanted to know if there was something on GitHub to signal that i am currently working on that issue (other than saying it in the comment).

**Comment by WaffleBuffer** [comment]
Indeed, i don't see a way to add me as assignee.

**Comment by schwabdidier** [comment]
done
