### ISSUE TITLE
Game Idea : Memory

### ISSUE THREAD

**Issue by MelanieCarriere** [schwabdidier/GazePlay#188]
Implement the famous game Memory for the eye tracking technology.
A certain number of cards (may vary to increase difficulty) are turn to hide its content. 
The aim of the game is to return the 2 cards having the same content.
The game makes work the player’s memory.

**Comment by schwabdidier** [comment]
On this subject http://www.bloghoptoys.fr/3-astuces-booster-memoire-de-travail

**Comment by schwabdidier** [comment]
Released in version 1.3 #217
