### ISSUE TITLE
New Game Idea (Catch the Biboules X Defend New-York)

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#189]
[Catch the Biboules X Defend New.pdf](https://github.com/schwabdidier/GazePlay/files/1681011/Catch.the.Biboules.X.Defend.New.pdf)

This game can improve the accuracy and reflexes of the children by giving an environment that suit well with their tastes (Cartoons etc...). It have been thought in the way of beeing not so tiring for the user but it can be adapted to be “harder”: Enemies could get closer faster for example.

In these games user could identify himself with one of these heroes.  It will also help to improve the reflection/thinking os the user (we have to think about an order when looking at enemies, they don't have to be too close.) We could also add a life bar to improve this skill maybe.

**Comment by schwabdidier** [comment]
I love Biboules :)
