### ISSUE TITLE
Game Idea : The chemist

### ISSUE THREAD

**Issue by MelanieCarriere** [schwabdidier/GazePlay#190]
At the center of the screen, there is a beaker. 
Around it there are some flacons containings Chemical products. 
The gamer chooses the product that he wants to add to the beaker. 
The choice is made by watching (a certain time) a chemical.
Depending to the products already in the beaker, a chemical reaction can occur.
This game permits to learn and to discover some chemical reactions.

**Comment by schwabdidier** [comment]
What would be abilities involved ? Skills developed by user ?

**Comment by MelanieCarriere** [comment]
From the eye-tracking technology point of view : validate a choice with the sight.

**Comment by schwabdidier** [comment]
it can be a funny game with explosions or other effects.

**Comment by schwabdidier** [comment]
Very close to magic potion ?

**Comment by johzz-o2** [comment]
@schwabdidier  yes , but instead of "chemical reactions" there are color fusions in magic potions :)

**Comment by schwabdidier** [comment]
yes ! Your game is better because it achieves an education goal.
