### ISSUE TITLE
Refactore style sheets to use base.css

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#191]
We should add one main style sheet so themes CSS contain only color changes (and not a repetition of the entire application CSS).

**Comment by WaffleBuffer** [comment]
I see a base.css, so is the issue fixed ?

**Comment by YannRobert** [comment]
@WaffleBuffer it's a good idea to refactor all existing CSS files to avoid repetitions.

IMO common styles can be moved to ```base.css```.
