### ISSUE TITLE
Game idea : The Carpenter

### ISSUE THREAD

**Issue by Skullhack** [schwabdidier/GazePlay#198]
I am proposing a new game idea for GazePlay : The Carpenter.
The goal is to cut wood plank by following a line with the eyes. The lines will be simple at the beginning (straight lines), more complex (lines with bends) and even curved.
I thought of 2 different methods to "follow" the line.
      Method 1 : Stare at a "start" point, follow the line up until the "finish" point, with an error margin that you can choose in settings. Looking too far away will stop the "cutting" and you'll have to start again from the beginning of from "checkpoints" along the lines for harder levels.
      Method 2 : You have to "validate" points along the lines by staring a few seconds at each of them, but in a precise order. This method is a lot easier and less frustrating since each point validated will work like a checkpoint, you'll never have to start again.

This game will develop the sens of observation of the child and learn him to follow a pattern with his eyes.

**Comment by schwabdidier** [comment]
Did you try to improve your idea or develop another one ?

**Comment by Skullhack** [comment]
I don't really know how I could improve this idea. Can you tell me what you think need to be improved ?
