### ISSUE TITLE
Counterintuitive start menu

### ISSUE THREAD

**Issue by twktheainur** [schwabdidier/GazePlay#2]
The start menu as a dropbox is somewhat counterintuitive, it doesn't showcase what the game can do very well. 

A regular game-style menu, with all the modes shown directly and accompanied by illustrative icons would probably be a better option here. 

If you make the options big enough and spaced enough (Big round icons with the text inside) you can make the whole thing gaze actuated (with very long gaze rest activations) and the child will be able to chose their activity directly.

**Comment by WaffleBuffer** [comment]
I'v started working on it. But in order to do something a minimum visual, i would like to know where is the css for the buttons like full screen button ?

**Comment by WaffleBuffer** [comment]
So, is this issue still opened ?

**Comment by schwabdidier** [comment]
If we summarize, we have 

"If you make the options big enough and spaced enough (Big round icons with the text inside)" : OK

It still lacks 
   - illustrative icons
   - gaze activation

But I guess, it should be better and easier to close this issue and to open this two last issues.

**Comment by YannRobert** [comment]
follow up issues : 
Main menu should have illustrative icons #215
Main menu should react to gaze events #216
