### ISSUE TITLE
Homescreen game variant chooser windows doesn't show in front when in full screen.

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#206]
Also it is kind of tricky to bring it to the front.
I think that the problem is from a conflict between fullscreen and model.
The main window is in full screen so no other window should be in front of it.
However the dialog one is modal so the main window won't respond unless we close (one way or another) the dialog window.

**Comment by schwabdidier** [comment]
On mac os, it works very well.

**Comment by WaffleBuffer** [comment]
I'm on Linux Mint Sylvia 18.2 with Cinnamon desktop

**Comment by YannRobert** [comment]
Probably depends on screen resolution.
A screenshot may help.

**Comment by WaffleBuffer** [comment]
![capture du 2018-02-07 15-10-01](https://user-images.githubusercontent.com/1880637/35920757-0c109314-0c19-11e8-8d42-bd3ed5270f08.png)

The problem is that the window won't even show in front of the full screen one. Maybe it's an isolated bug

**Comment by WaffleBuffer** [comment]
This is closed
