### ISSUE TITLE
Game idea : Divisor

### ISSUE THREAD

**Issue by givaudanv** [schwabdidier/GazePlay#208]
In this game, you start with a big "bubble" that move slowly on the screen. When you look at it, it divide into smaller, faster bubbles. This can be repeated multiple times, until the smallest bubble simply pop.
The theme is free, I thought of slime as circles that you have to clean, but anything can do.
A score can be added, based on the time you took to completely clean the screen of every bubbles, to compare and see improvement.
As settings, I can think of :
- The "level" of the bubbles (the number of time it divide)
- The speed of the bubbles
- The theme, if they are more than one

This game can improve the accuracy and the speed of the player, as well as being funny depending on the theme used.

**Comment by schwabdidier** [comment]
Nice idea.

With theme, what do you mean ?

**Comment by Skullhack** [comment]
Thanks !
By theme, I meant the visual theme : image on the bubbles as well as the background.

**Comment by schwabdidier** [comment]
done
