### ISSUE TITLE
Images for games

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#222]
We need images to illustrate games (now this are only smileys)

**Comment by YannRobert** [comment]
What about simple screenshot of the game? at least as a start. 
Could even be an gif or webm animation?

Off course an art work would be better.

**Comment by schwabdidier** [comment]
oh, you're right !

**Comment by WaffleBuffer** [comment]
This one could be closed i think.

**Comment by schwabdidier** [comment]
if we can have better images, it would be better :)

**Comment by YannRobert** [comment]
Yes, should create a new issue "better images for game menu", so that current issue can be closed and set in the release 1.3 milestone "changelog"
