### ISSUE TITLE
Background sound

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#248]
I can't create music on my own, 
but we could use music with creative commons licenses.

**Comment by schwabdidier** [comment]
yes, creative commons licenses and/or personal music throw configuration

**Comment by YannRobert** [comment]
Here is a quick selection of musics from opengameart.org
Please check individual license before using.

https://opengameart.org/content/enchanted-festival
https://opengameart.org/content/happy-arcade-tune
https://opengameart.org/content/menu-music
https://opengameart.org/content/one
https://opengameart.org/content/tower-defense-theme
https://opengameart.org/content/space-dimensions-8bitretro-version
https://opengameart.org/content/snowfall
https://opengameart.org/content/peaceful-place
https://opengameart.org/content/acrostics
https://opengameart.org/content/copycat
https://opengameart.org/content/happy-tune

**Comment by schwabdidier** [comment]
Wow, this Website looks amazing !!

**Comment by YannRobert** [comment]
I'm wondering if sound files should be included into the distributed zip file
or if it should be downloaded by the game (on first use, or as a batch download when user want to download all tunes at once for later offline usage)

I like the 'download on first use' solution.
This will keep the distributed file very light.

The batch download solution can then be added too. In order to allow easy offline usage.

Moreover, this will not clutter the git repository with binaries.

Then adding a tune would be as simple as just providing a url for it.
Can be easily customized by end user too.

**Comment by YannRobert** [comment]
Providing sound URL instead of sound file content would also simplify the licensing issue.

**Comment by schwabdidier** [comment]
I definitely like the idea of music ! I want more !
