### ISSUE TITLE
Better images for game menu

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#260]

**Comment by WaffleBuffer** [comment]
Is this linked to issue #448 ?

**Comment by schwabdidier** [comment]
I don't thing so

**Comment by WaffleBuffer** [comment]
So what about is it exactly ?

**Comment by schwabdidier** [comment]
For now, images are screenshots of the game. We can improve it with more artistic images maybe.

**Comment by kuhlkrein** [comment]
I can try to do it after the Gaze Menu and version 1.4 maybe ?

**Comment by schwabdidier** [comment]
Sure !

**Comment by schwabdidier** [comment]
of course !

**Comment by kuhlkrein** [comment]
Begining of new images started from yesterday night:  #551

**Comment by schwabdidier** [comment]
done
