### ISSUE TITLE
Use a common ProgressIndicator

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#261]
Many games use an animated progress indicator. I don't know if it is really relevant be we could make a common GazeProgressIndicator with a common fixDuration.

**Comment by schwabdidier** [comment]
Yes certainly.

For information, last week I wrote something about "selection skill"

Selection with eye-tracker is not as easy as it is with a mouse. Blink is both not easy to capture with an eye-tracker and often very difficult to perform for a child with multiple disabilities. In AAC programs, an usual way to select an element (photo, image, pictogram, etc.) is to keep the gaze on this element. It is called, a dwell interaction \cite{Jacob:1990:YLY:97243.97246}.  A feedback is given as a circular progress bar. When it is full after a configurable time, the element is selected.
