### ISSUE TITLE
Game idea : Colors!

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#268]
This game would learn the selection selection and action linked to this selection.
The game would simply consists of a drawing with a toolbox somewhere containing a list of colors.
When you look at a zone for a certain time, that would colorize this zone with the current selected color.
Some points that i haven't really researched yet : 
- Is it possible to do it from a custom image ? (without predefined geometries like rectangles)
   -> take as input a colored image and transform it as a black and white only
- Is it possible to save the result as an image (even to add a print functionality).

This kind of activities exists in some educational games. The overall game would actually be like the fill functionality of Paint software or other graphical software.

**Comment by YannRobert** [comment]
I started a basic drawing game some time ago. It's not available from the game menu yet.

**Comment by WaffleBuffer** [comment]
I saw it but has it been tested with an eye tracker? I'm not that eye drawing is doable due to saccades in look. My idea is more about coloring an existing drawing.

**Comment by schwabdidier** [comment]
Your two games are very different. I love the one you did Yann. Lots of colors. Waffle's idea is more coloring. And I think it can be a fantastic game.

**Comment by WaffleBuffer** [comment]
I think this issue can be closed
