### ISSUE TITLE
Registration to the 10ème Challenge Handicap et Technologie 

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#279]
@YannRobert : For information. As it is a challenge for students and GazePlay involve students, we would like to participate. http://ifrath.fr/cht/index.php

@MelanieCarriere @WaffleBuffer @Skullhack @kuhlkrein @DMyTryC
Students, please manage the registration. Of course, I check everything before sending the mail.
http://ifrath.fr/cht/inscription.php

- DESCRIPTIF DU PROJET : 1 page to write

- Video : I am pretty sure, we can make a new and better than mine

**Comment by WaffleBuffer** [comment]
The picture that they ask is a picture of the project or a photo of ourself ?

**Comment by schwabdidier** [comment]
The logo I guess

**Comment by WaffleBuffer** [comment]
So, if i understand correctly, we should make only one registration file ? Does someone in particular take care of it, because i've begun to fill it, however i don't have everyone's full name.
Here it is.
[CHT2018_Inscription.pdf](https://github.com/schwabdidier/GazePlay/files/1780081/CHT2018_Inscription.pdf)

**Comment by schwabdidier** [comment]
Good. Maybe you can put it on an open drive to permit us to edit.

**Comment by WaffleBuffer** [comment]
https://mypads.framapad.org/mypads/index.html?/mypads/group/ter-gazeplay-l1wgq71t/pad/view/cht2018-inscription-frwjq74o

**Comment by WaffleBuffer** [comment]
As you said in your mail, we won't go to this event so i guess we can close this issue.

**Comment by schwabdidier** [comment]
yes :(
