### ISSUE TITLE
Colors : some ideas for colorings

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#290]
@WaffleBuffer :

https://www.publicdomainpictures.net/view-image.php?image=156578&picture=girl-amp-dog-coloriage&jazyk=FR

https://pixabay.com/fr/coloration-livre-de-coloriage-1293901/

Don't forget to check licence.

**Comment by WaffleBuffer** [comment]
For now, the default image is just for me to test. In the end it would be possible to colorize users images.

**Comment by WaffleBuffer** [comment]
Also using this website's images urls don't work for some reason. But in the end i will use local images rather than website url.

**Comment by schwabdidier** [comment]
Now anyone can add new coloring images
