### ISSUE TITLE
Separation gazePlay - eye trackers servers

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#3]
Two reasons :
- some eye trackers API are not in Java
- for eye tribe, doesn't seem to work in an executable jar (resolved, gson.jar problem, see below)

**Comment by twktheainur** [comment]
You may want to use something like opensoundcontrol (osc) http://opensoundcontrol.org/introduction-osc for communications between the client and the servers

It's meant for real-time message passing for audio/media applications and has bindings for most major languages (including c, c++, java, which should cover most eye tracker apis)

**Comment by schwabdidier** [comment]
Sockets should be enough, I just need to transfert coordinates (=text).

**Comment by schwabdidier** [comment]
I resolved the bug. In fact, it doesn't work (and throws no exception) when  gson.jar is not in the classpath nor executable jar. So there is only reason 1. Is it a good idea to do that ? I will see when I have a tobii to test.

**Comment by schwabdidier** [comment]
Not needed. We integrated Tobii low cost eye-trackers through JNI (Java Native Interface) and eye tribe work fine even with jar.
