### ISSUE TITLE
Cup pass pass problème "hitbox "

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#304]
Hello, On the game with the cup there is a problem related to the hitboxes when using the mouse... They look a bit "random" and seems to be enabled only on the bottom border of the cups. I tried to debug it using image views instead of rectangles but no way...

**Comment by schwabdidier** [comment]
odd, it was working previously @DMyTryC

**Comment by kuhlkrein** [comment]
I don't know, I had lot of nullpointer execption errors and when I fixed it I had this problem.

**Comment by kuhlkrein** [comment]
Syr, my mistakes, I forgot to uncomment a line :) It works fine now, no error :) We can close the issue @schwabdidier
