### ISSUE TITLE
bug coloring 

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#322]
When selecting color with eye tracker, there is a bug. 
@WaffleBuffer

**Comment by WaffleBuffer** [comment]
What bug exactly ? Also, you should now that trying to change the custom color make the program crash.

**Comment by WaffleBuffer** [comment]
I confirm after testings that some time to time, GazePlay will throw the same exception over and over about not being able to update gaze position followed by an IndexOutOfBoundException.

**Comment by schwabdidier** [comment]
Please copy paste error then try to find the bug.

**Comment by WaffleBuffer** [comment]
I havn't access to the eye tracker for now but when i do i will

**Comment by schwabdidier** [comment]
You can find it in your logs. In you can't find it, the eye tracker is upstairs

**Comment by WaffleBuffer** [comment]
Where are the logs of games ? Also, the exception i get in the console is :

**Comment by WaffleBuffer** [comment]
The error seems to come randomly when we want to select something inside the color tool box

**Comment by schwabdidier** [comment]
continue your work on that problem

**Comment by WaffleBuffer** [comment]
I think i succeeded in getting around the problem. I guess it needs further tests but it should be good.

**Comment by schwabdidier** [comment]
thank you
