### ISSUE TITLE
very difficult to color a part 

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#323]
I guess the zone is too tiny

**Comment by schwabdidier** [comment]
@WaffleBuffer

**Comment by WaffleBuffer** [comment]
If it is that, then it really depends on the drawing and the eye tracker. I'm not sure if i can do something about.

**Comment by WaffleBuffer** [comment]
Is this still an issue ? (gaze event positions were corrected by a previous PR so if that was the origin of the issue is should be closed)
