### ISSUE TITLE
piano doesn't work in jar 

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#324]
@kuhlkrein

**Comment by kuhlkrein** [comment]
Probably because of some path problem, I will try to solve it thank you.

**Comment by kuhlkrein** [comment]
j'ai oublié de le préciser dans ma derniere request mais normalement ce bug devrait être corrigé (il est un peu plus long à charger que les autres par contre j'ai l'impression)

**Comment by YannRobert** [comment]
When talking about an other pull request, please provide the id to create crossed-reference
