### ISSUE TITLE
Game idea : Order

### ISSUE THREAD

**Issue by givaudanv** [schwabdidier/GazePlay#331]
This game is based on memory : some target will appear on the screen in a certain order. The player will have to memorize this order, then the target will flip. The player will then look at the target one by one, revealing their number. If the correct order is respected, the player win. Else, he can retry.

This game will train the memory of the player and his focus.

**Comment by schwabdidier** [comment]
Very good idea. Go !

**Comment by Sannaraek** [comment]
I am currently on this idea!

**Comment by schwabdidier** [comment]
@Sannaraek sorry, it already exists.
