### ISSUE TITLE
Parameters menu could use a scroll bar

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#345]
With the increasing number of parameters in the parameters menu, a scroll could be nice. Especially when using in windowed mode.

**Comment by schwabdidier** [comment]
Yes, it is definitely a good idea.

**Comment by DMyTryC** [comment]
I was thinking about changing the vgap from a static value to one depending on the screen size

**Comment by DMyTryC** [comment]
And if noone is assigned to this, I would like to be assigned to it

**Comment by schwabdidier** [comment]
It is ok

**Comment by WaffleBuffer** [comment]
@YannRobert I am quite sure that you didn't want to assign this to me but to @DMyTryC  ^^
