### ISSUE TITLE
Proposition : mascott

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#347]
I saw the little biboule in multiple games. Could it be nice to use it as a mascott ? We could add it in the defaults images (for ninja, block...).

**Comment by schwabdidier** [comment]
I really like biboules, yes, it is a good idea

**Comment by schwabdidier** [comment]
It is our mascott for a while (thanks @WaffleBuffer for the idea and, of course, @kuhlkrein for Biboules)
