### ISSUE TITLE
Game Idea: Got a Pet

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#352]
I don't know how we could create such a game, but I've read that in most of the case, some children with multiple disabilities have to deal with the same people, the same environement, every days. 
In some case it's not a "problem" because people around them interract with them etc, but sometimes it can be hard to understand what is a "social interraction" and an emotion for these children. Maybe we could try to create a kind of "virtual pet",or something like this, to make them learn what is happyness, sadness, fear, love, anger... (Without going so far in details because it have to be understandable by each of them)
It would be probably a bigger project but could be an interresting one. 

![image](https://user-images.githubusercontent.com/24478346/39706340-6939f650-5211-11e8-9c6d-1db364ecd68a.png)

![image](https://user-images.githubusercontent.com/24478346/39706358-772fe1e8-5211-11e8-8ce4-9f39786fefbd.png)

**Comment by kuhlkrein** [comment]
Maybe with a Biboule ?

**Comment by schwabdidier** [comment]
done
