### ISSUE TITLE
CakeGames: When do we win ?

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#370]
The problem is that I don't know if the principle of the game is too complex or not (depend on the abilities of the user I suppose).
At the begining I added up and down button to move on the different layers of the cake (to modify the previous layer for example) but finaly I removed it because their are to many button.

For now what I'm doing is that when we click on validate we count the number of good matches between the cake asked by the computer and the one cooked by the user and we add it to the score of the stats. Then we create a new instance of the game.

**Comment by schwabdidier** [comment]
There is a game like this in the grid 3. You can be inspired by it. When you choose a ingrédient it goes on the cake and you can't change anymore. When the cake has enough ingrédients (5 ?) it stops and there is a little animation.

**Comment by kuhlkrein** [comment]
Oh yes I see it's a good idea thanks ! I think I will create one version where the user is free to create the cake he want, and another version like this ! :)
