### ISSUE TITLE
GazeEvent position

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#374]
I have noticed this issue some time ago but i forget to write it down.
When receiving a GazeEvent, calling the method `getX()` or `getY()` (to have the event position) will return the position on the screen and not on the node. This is a consistency issue because calling the same methods on a MouseEvent on the same position will return a very different result. The problem is visible on the colors game when not playing in full screen for example.

**Comment by kuhlkrein** [comment]
Did you tried to fix it with a screenToLocal() call ?

**Comment by WaffleBuffer** [comment]
Thank you ! It works perfectly.

**Comment by schwabdidier** [comment]
So we can close this issue.
