### ISSUE TITLE
General Progess Button for the menu ?

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#377]
For my cake game I'm currently trying to implement a general circle button with a progressIndicator (using the code implemented in the magiccard game) that can be activated by pressing the mouse and that could be activated with gaze (this part is not done yet, the indicator works fine but the event is not yet implemented/fired). So, I was thinking maybe we could try to use this idea to change the menu button, so the user can navigate everywhere only using his gaze... ?

**Comment by kuhlkrein** [comment]
Ok so when I'll finish this class I will put it into the util package and try to do something for the main menu & controlBar :)

**Comment by WaffleBuffer** [comment]
I created some generic classes for gaze progress indicators in the colors package. These classes are IGazeProgressIndicator, AbstractGazeIndicator, GazeProgressIndicator (about the same as in magic cards) and GazeFollowerIndicator. The last one is the same as in the color game : a little gaze indicator that follow the gaze.
Maybe it won't be useful for you but i wanted to notice you that they exist ^^.

**Comment by schwabdidier** [comment]
Please, check that @kuhlkrein and discuss together (IRL and in your mother language is better :) ). Propose a solution.

**Comment by kuhlkrein** [comment]
Ok @schwabdidier , sry I didn't see your message. All the button seems to work fine(I only tested with mouse event but gazeevent should work too), my only problem is that the progressIndicator is not displayed on the screen yet, but I know what is the problem. @WaffleBuffer just show me what he've done so I will check if something can help me ;)
