### ISSUE TITLE
can't click on options

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#392]
@kuhlkrein 

When gazeplay asks dimensions, I can't click anymore.

**Comment by kuhlkrein** [comment]
When you move from fullscreen to windowed screen ?

**Comment by schwabdidier** [comment]
no always

**Comment by kuhlkrein** [comment]
what do you mean by "gale asks dimensions" ? I just noticed that we can't click on the fullscreen button, is that what you're saying ?

**Comment by schwabdidier** [comment]
updated

**Comment by kuhlkrein** [comment]
Ok I think I know how to fix it.

**Comment by kuhlkrein** [comment]
@schwabdidier  is that ok for u with my last pull request ?

**Comment by schwabdidier** [comment]
yes !
