### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#394]
Order @Skullhack 
Cakes @kuhlkrein

**Comment by schwabdidier** [comment]
ask to other students if you don't understand

**Comment by Skullhack** [comment]
Oh sorry I was reading "Transition" ! :/

**Comment by kuhlkrein** [comment]
I added mine for cakes

**Comment by kuhlkrein** [comment]
We can close this one @schwabdidier .
