### ISSUE TITLE
statistics for color it

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#396]
@WaffleBuffer  Are they relevant ? Do we need statistics ?

**Comment by WaffleBuffer** [comment]
Maybe at least the heat map can be useful. The only thing measured for now is the number of zone being colored.

**Comment by WaffleBuffer** [comment]
Is this still an issue ?

**Comment by schwabdidier** [comment]
no, you are right :)

Only 14 months to answer issue :D
