### ISSUE TITLE
Volume doesn't affect sound effects

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#402]
Some games (like bubble of ninja) have sound effects which are not affected by volume property.

**Comment by YannRobert** [comment]
The way I see it, this is expected.
Background music volume controller only controls background music volume.
If you need sound effects volume control, then you need a new dedicated controller.

**Comment by WaffleBuffer** [comment]
The problem then resides in the UI where it is written only "Volume" so user will naturally think that it controls the whole application volume.

**Comment by WaffleBuffer** [comment]
Actually, it is written "music" above volume but then it is still the only volume slider

**Comment by WaffleBuffer** [comment]
This can be closed
