### ISSUE TITLE
ProgressButton doesn't work

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#419]
The progressButton, progressHomeButton, progressPane... don't work with the gaze events..

**Comment by kuhlkrein** [comment]
I tried eventHandler and eventFilter but none is working

**Comment by WaffleBuffer** [comment]
Have you tried adding this line : 
`gazeDeviceManager.addEventFilter(node);` from a GazeDeviceManager object ?
I had the same issue with my GazeProgressIndicator.

**Comment by kuhlkrein** [comment]
Ok I will try thank you !
