### ISSUE TITLE
Configuration button misplaced

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#422]
The configuration is misplaced.
By default it is like that (the button is in the bottom left of the screen nearly completely off screen)
![capture du 2018-05-23 16-29-52](https://user-images.githubusercontent.com/1880637/40430991-b118c3f6-5ea6-11e8-9829-5f4bd2d1b5d7.png)

But if get into windowed mode and back in fullscreen again i get this (with configuration panel expended) : 
![capture du 2018-05-23 16-20-29](https://user-images.githubusercontent.com/1880637/40430550-aa91bf02-5ea5-11e8-845c-ff8a4be3a113.png)

**Comment by kuhlkrein** [comment]
Ok,  it really depend on OS.  I will try to fix it,  you're on linux ?

**Comment by WaffleBuffer** [comment]
I'm on Linux Mint with a resolution of 1920*1080px. Also i just realized that on some games there is no problem (like the magic cards game for example).

**Comment by WaffleBuffer** [comment]
@kuhlkrein are you still working on it? I've nearly come to a working solution.

**Comment by kuhlkrein** [comment]
@WaffleBuffer I was working on something else for now so if you have a solution it's perfect ^^

**Comment by kuhlkrein** [comment]
We still have a problem when we're not in fullscreen mode and we launch a game, the cofig doesn't appear. we have to turn on / off again the fullscreen mode to make it appear

**Comment by WaffleBuffer** [comment]
With the last version do you still have the issue @kuhlkrein ?
