### ISSUE TITLE
Gaze Menu not yet implemented

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#427]
I tried to use the menu with gaze, and sincerly, even without talking about errors returned by terminal, it's not really usable... (to much things on the screen at the same time, hard to select an element and easy to select one by mistake...) I think I will put this idea to trash and maybe delete the "progress" class.

@schwabdidier  what do you think ?

**Comment by schwabdidier** [comment]
It is a better idea then you closed or it is Stills à bad idea ?

**Comment by kuhlkrein** [comment]
Then I close haha.
But there are some exception thrown by gazeplay and I don't know if it's about what I'm trying to add or if it's about tobii itself

**Comment by kuhlkrein** [comment]
Beta version code : #490

**Comment by kuhlkrein** [comment]
I think that with the new version of the tobiiGazeDeviceManager, the gaze menu will be more stable now, I will try to add some modifications soon.

**Comment by schwabdidier** [comment]
no more needed
