### ISSUE TITLE
A Background for the menu ?

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#448]
What do you think if we were adding a background for the menu ? it looks a bit dark for now. I added a line on my new pull request #447.
Of course we can change the image but I think it looks a bit more colored :)

**Comment by WaffleBuffer** [comment]
There was at some point some test about an infinitely scrolling background in pixel art

**Comment by kuhlkrein** [comment]
Yes I think it was Yann, this one is just a basic picture, stretched on the whole scrol pane. :)

**Comment by schwabdidier** [comment]
It is a kind of video. Maybe we can disable it with an option and add something in the configuration to upload our own photo ?

**Comment by WaffleBuffer** [comment]
Maybe this would be too much customizing. I mean, it's only the main menu, it's not where the user will spend most of his time. Also, for now it's not a video but a GIF picture.

**Comment by kuhlkrein** [comment]
As you want @schwabdidier and @WaffleBuffer , it was just an idea to try to create something a bit more fun :)
