### ISSUE TITLE
Problem on windows with logo code

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#478]
I'm sorry @schwabdidier  I just realized that I Push the code with the commented logo part because on windows it's throwing an error (maybe a file name impossible to use in windows [<,>,!,? symbols ?]) . Do you see something that can throw this error @WaffleBuffer  in your code ?

**Comment by WaffleBuffer** [comment]
You can see my changes on my commit here : 
https://github.com/schwabdidier/GazePlay/pull/472/commits/7b80adbbf6af516892c5742463cc0767b9b036a2
