### ISSUE TITLE
Shooter items position issues

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#479]
Lot of items position issues due to #476 . Be careful @WaffleBuffer when correcting some issue, the background is ok now but the item position is misplaced because of the original size of the panel when launching the game. It's better to have a black rectangle keeping the good position of all elements rather than fixing position only :) I'm fixing it now

**Comment by WaffleBuffer** [comment]
Ok sorry to introduces more issues ^^'. I thought positions will update dynamically (i tried to do it for end point positions at least)

**Comment by kuhlkrein** [comment]
Yes thanks for the update function on end points :) I'm creating other ones for different items
