### ISSUE TITLE
Proposition : make the configuration button in game appears on mouse over

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#482]
The configuration is not useful for most of the play time. It could be better if it appears only if needed. I propose to make it appear at the beginning (to show where it is) then makes it invisible until the mouse (and not the gaze) goes over its position. This could be useful if the gaze events can be triggered on what's behind configuration button while it's invisible.

**Comment by kuhlkrein** [comment]
Gaze event doesn't care about which item is over which one. (I have to do a pull request about that thing actually), so there is no problem with this part for now. (Even if we will have to modify it later , if we manage to solve the event problem.)

**Comment by kuhlkrein** [comment]
Btw,  I'm not sure but I think there's a problem in the color game related to that. When selecting a custom color I think that at the same time it's coloring the drawing behind the custom color window . Idk how to solve this issue for now..

**Comment by WaffleBuffer** [comment]
Hmm... I did encounter this problem and i thought i fixed it. Normally, when opening the custom color picker, the drawing is disabled until the custom color window is closed.

**Comment by WaffleBuffer** [comment]
For me, it was working correctly (there was not drawing while selecting a custom color, but the pictures wern't updating correctly. I fixed it in my last PR.

**Comment by kuhlkrein** [comment]
Ok no problem :) But yeah, most of the time the gaze events are going through all the items, without checking the depth.
