### ISSUE TITLE
File.separator and so Utils.FILESEPARATOR return "\" instead of "/" on windows

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#488]
leading to #478 , #436  (and maybe #390)

For now, I fixed it by replacing by "/", cf pull request #487

**Comment by WaffleBuffer** [comment]
Actually, on Windows it is normal to use "\" instead of "/" for file path (you can see this by looking at any file properties). However it is weird that it causes troubles...

**Comment by kuhlkrein** [comment]
Yeah I know that's why I didn't understand the fact that it leads to an error... Maybe it was a concatenation of strings with / and other with \ but the path displayed was containing only \

**Comment by WaffleBuffer** [comment]
Well, if the fix works...

**Comment by schwabdidier** [comment]
it works !
