### ISSUE TITLE
Provide a way to build from source with only 1 command line

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#49]
Hi Didier,

I think GazePlay is interesting. Thank you for this.

I would like to build the project from source.

It does not contain any instruction on how to build it, 
and it does not include project files to build it with either Maven or Gradle.

I believe this is a requirement in order to have contributors on the project.

**Comment by schwabdidier** [comment]
In fact, if you open it in a IDE (IntelliJ or eclipse for instance), it should work. But, it is true to generate jars, I should use maven...

**Comment by schwabdidier** [comment]
btw, thank you very much for your comment, feel free to ask any question.

**Comment by schwabdidier** [comment]
Thank you very much for Maven. It seems to work very well. Really easy to use. Again, Thanks.
