### ISSUE TITLE
Travis "Issue" file encoding

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#501]
I remember that, when opening a file, the cleaning/installation was going well on the local machine, but on Travis he was asking for the specification of the encoding style so I had to write:

Scanner sc = new Scanner(new FileInputStream("file.txt"), "UTF-8");
instead of just 
Scanner sc = new Scanner(new FileInputStream("file.txt"));

just to notice that difference.

**Comment by kuhlkrein** [comment]
CF the 2 last commits in the PR #291

**Comment by kuhlkrein** [comment]
other problem of the same kind here : #508

**Comment by kuhlkrein** [comment]
deadstore #553

**Comment by schwabdidier** [comment]
No more problem
