### ISSUE TITLE
GazePlay 1.4

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#513]
New features : 
        - profiles : now several profiles can be used (including images and configurations) in order to permit utilisation with several users (for specialized institutions for instance)
        - new menu
        - white or black background (to increase contrast for some kinds of disabilities)
        - No more Black bar in the bottom side (now games use all the screen)
        - Configuration button is very light (low opacity)
        - music level can be configured for each game
        - sound level can be configured for each game
        - speed level can be configured for each game

New games :
        - mole (hit the biboules in a Whac-A-Mole like game) 
        - cake game (build your own cake)
        - Labyrinth (help the mouse to find cheese)
        - Piano (play the piano, add your own music)
        - color (take any image, it can be transform to black and white and the paint)
        - the room (explore a bedroom)
        - order (some targets appear one after one, shoot them in the same order)
        - Pet game (take care of a small biboule! give him shower, feed him and make him do some sports in the park !)

Various improvements in games/bugs resolved (see issues in Github for more information)

---------------------------------------------------

Nouvelles fonctionnalités : 
        - profils : plusieurs profils peuvent maintenant être utilisés (y compris les images et les configurations) afin de permettre une utilisation avec plusieurs utilisateurs (pour les institutions spécialisées par exemple).
        - nouveau menu
        - fond blanc ou noir (pour augmenter le contraste pour certains types d'handicaps)
        - Plus de barre noire dans la partie inférieure (maintenant les jeux utilisent tout l'écran)
        - Bouton de configuration très estompé (faible opacité)
        - le niveau de musique peut être configuré pour chaque jeu
        - le niveau sonore peut être configuré pour chaque jeu
        - la vitesse peut être configurée pour chaque jeu

Nouveaux jeux :
        - taupe (frapper les biboules dans un jeu de type jeu-de-la-taupe) 
        - jeu de gâteaux (construisez votre propre gâteau)
        - Labyrinthe (aide la souris à trouver le fromage dans le labyrinthe)
        - Piano (jouer du piano, ajouter votre propre musique)
        - couleur (prendre n'importe quelle image, elle peut être transformée en noir et blanc et la peinture)
        - la pièce (explorez une chambre à coucher)
        - ordre (certaines cibles apparaissent l'une après l'autre, touchez-les dans le même ordre)
        - Jeu d'animaux de compagnie (Prenez soin d'un petit biboule, donnez-lui une douche, nourrissez-le et faites-lui faire du sport dans le parc!)

Diverses améliorations dans les jeux/bugs résolus (voir les problèmes dans Github pour plus d'informations).

**Comment by schwabdidier** [comment]
Please @kuhlkrein complete when you have time.
@YannRobert we plan to release it soon. Tuesday or Wednesday when I am in Grenoble next week would be the best.

**Comment by YannRobert** [comment]
Sorry I did not participate much in this release.

**Comment by schwabdidier** [comment]
Nevermind, same for me. Students did it !

**Comment by schwabdidier** [comment]
@kuhlkrein can you describe the last game ? :)

**Comment by kuhlkrein** [comment]
@schwabdidier  :

(Take care of a small biboule! give him shower, feed him and make him do some sports in the park !)

(Prenez soin d'un petit biboule, donnez-lui une douche, nourrissez-le et faites-lui faire du sport dans le parc!)

**Comment by schwabdidier** [comment]
released  !
