### ISSUE TITLE
User Properties

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#514]
I just would like to have your advice about the properties for the users.
What I'm planning to do is to create a directory "users", like this:
![image](https://user-images.githubusercontent.com/24478346/42094084-ea388976-7bae-11e8-87f5-e27c87d51d14.png)
Inside we should find one directory per user, containing the properties and images folder right?
![image](https://user-images.githubusercontent.com/24478346/42094152-221eed4e-7baf-11e8-8f11-ef9a0a513187.png)
For now, the properties of each user added (manually) are loaded in a good way, I have to generate them automatically when adding a new user but I want to be sure that it's the best way of doing...

**Comment by YannRobert** [comment]
IMO "profiles" is a better name that "users"

As a single user may want to switch between multiple profiles

**Comment by kuhlkrein** [comment]
Ok no problem, I was just using the Windows notation ;)
