### ISSUE TITLE
What does the samplesAmela contains ?

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#546]
Is that some games that we could try to integrate?

**Comment by schwabdidier** [comment]
No. It is already done.

**Comment by kuhlkrein** [comment]
So maybe we can remove the package no ?

**Comment by schwabdidier** [comment]
good question :) Certainly, yes

**Comment by schwabdidier** [comment]
I have deleted branches

**Comment by schwabdidier** [comment]
I have deleted unused code
