### ISSUE TITLE
mvn clean  license:add-third-party problem

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#549]

**Comment by schwabdidier** [comment]
I first tried complete line 

`mvn clean license:download-licenses license:add-third-party release:prepare `

Error

then I tried to decompose

`mvn clean license:download-licenses`

It works but

`mvn  license:add-third-party ` doesn't

`[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] gazeplay-project
[INFO] gazeplay-commons
[INFO] gazeplay-data
[INFO] gazeplay
[INFO] gazeplay-side-projects
[INFO] gazeplay-picto-pick
[INFO] gazeplay-melordi
[INFO] gazeplay-dist
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gazeplay-project 1.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- license-maven-plugin:1.14:add-third-party (default-cli) @ gazeplay-project ---
[WARNING] The goal is skip due to packaging 'pom'
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gazeplay-commons 1.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- license-maven-plugin:1.14:add-third-party (default-cli) @ gazeplay-commons ---
[WARNING] The license for jaxen--jaxen--1.1.6 has no name (but exist)
[INFO] Load missing file /Users/schwab/Documents/GazePlay/gazeplay-commons/src/license/THIRD-PARTY.properties
[INFO] Missing file /Users/schwab/Documents/GazePlay/gazeplay-commons/src/license/THIRD-PARTY.properties is up-to-date.
[WARNING] There is 2 dependencies with no license :
[WARNING]  - dom4j--dom4j--1.6.1
[WARNING]  - net.jcip--jcip-annotations--1.0
[WARNING] There is 2 dependencies with no license :
[WARNING]  - dom4j--dom4j--1.6.1
[WARNING]  - net.jcip--jcip-annotations--1.0
[INFO] Writing third-party file to /Users/schwab/Documents/GazePlay/gazeplay-commons/target/generated-sources/license/THIRD-PARTY.txt
[INFO] Regenerate missing license file /Users/schwab/Documents/GazePlay/gazeplay-commons/src/license/THIRD-PARTY.properties
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gazeplay-data 1.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- license-maven-plugin:1.14:add-third-party (default-cli) @ gazeplay-data ---
[WARNING] The license for jaxen--jaxen--1.1.6 has no name (but exist)
[INFO] Load missing file /Users/schwab/Documents/GazePlay/gazeplay-data/src/license/THIRD-PARTY.properties
[INFO] Missing file /Users/schwab/Documents/GazePlay/gazeplay-data/src/license/THIRD-PARTY.properties is up-to-date.
[WARNING] There is 2 dependencies with no license :
[WARNING]  - dom4j--dom4j--1.6.1
[WARNING]  - net.jcip--jcip-annotations--1.0
[WARNING] There is 2 dependencies with no license :
[WARNING]  - dom4j--dom4j--1.6.1
[WARNING]  - net.jcip--jcip-annotations--1.0
[INFO] Writing third-party file to /Users/schwab/Documents/GazePlay/gazeplay-data/target/generated-sources/license/THIRD-PARTY.txt
[INFO] Regenerate missing license file /Users/schwab/Documents/GazePlay/gazeplay-data/src/license/THIRD-PARTY.properties
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gazeplay 1.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- license-maven-plugin:1.14:add-third-party (default-cli) @ gazeplay ---
[WARNING] The license for jaxen--jaxen--1.1.6 has no name (but exist)
Downloading: https://jitpack.io/com/github/schwabdidier/gazeplay-commons/1.4.0-SNAPSHOT/gazeplay-commons-1.4.0-SNAPSHOT-third-party.properties
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gazeplay-project ................................... SUCCESS [  1.093 s]
[INFO] gazeplay-commons ................................... SUCCESS [  0.687 s]
[INFO] gazeplay-data ...................................... SUCCESS [  0.055 s]
[INFO] gazeplay ........................................... FAILURE [  1.422 s]
[INFO] gazeplay-side-projects ............................. SKIPPED
[INFO] gazeplay-picto-pick ................................ SKIPPED
[INFO] gazeplay-melordi ................................... SKIPPED
[INFO] gazeplay-dist ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.559 s
[INFO] Finished at: 2018-07-08T19:05:00+02:00
[INFO] Final Memory: 22M/265M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.14:add-third-party (default-cli) on project gazeplay: could not execute goal AddThirdPartyMojo for reason : ArtifactResolutionException: Unable to locate third party descriptor: Could not transfer artifact com.github.schwabdidier:gazeplay-commons:properties:third-party:1.4.0-SNAPSHOT from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized.
[ERROR] com.github.schwabdidier:gazeplay-commons:properties:1.4.0-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] bintray (http://jcenter.bintray.com, releases=true, snapshots=false),
[ERROR] jitpack.io (https://jitpack.io, releases=true, snapshots=true),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gazeplay

Process finished with exit code 1`

What is the problem @YannRobert  ? I think I did all needed.

**Comment by YannRobert** [comment]
fixed by commit https://github.com/schwabdidier/GazePlay/commit/6de92f04229315a2e1ac816d59c6beccd19d1f6b
