### ISSUE TITLE
Modification on the abstract device manager ?

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#554]
We definitely have a problem with the GazeEvent: adding a line
 "node.addEventFilter(GazeEvent.ANY,eventHandler)" don't work because we are looking at the nodes contained only in the root.
Let's assume that we have an HBox contained in this root. then the event will occur on the HBox, but the event defined for the nodes INSIDE the HBox are not fired because we are not going inside this HBox node.
I think a solution should be to check all the nodes that are instance of Pane(AnchorPane, BorderPane, DialogPane, FlowPane, GridPane, HBox, StackPane, TextFlow, TilePane, VBox...) [https://docs.oracle.com/javase/8/javafx/api/javafx/scene/layout/Pane.html] in order to apply this function recursively on each of these nodes...

Here is the function that I'm planing to change: 
`synchronized void onGazeUpdate(Point2D gazePositionOnScreen) {
        // log.info("gazedata = " + gazePositionOnScreen);

        notifyAllGazeMotionListeners(gazePositionOnScreen);

        final double positionX = gazePositionOnScreen.getX();
        final double positionY = gazePositionOnScreen.getY();

        Collection<GazeInfos> c = shapesEventFilter.values(); // Needn't be in synchronized block
        synchronized (shapesEventFilter) { // Synchronizing on m, not s!
            Iterator<GazeInfos> i = c.iterator(); // Must be in synchronized block
            while (i.hasNext()) {
                GazeInfos gi = i.next();

                final Node node = gi.getNode();

                // log.info("localPosition = " + localPosition);

                if (!node.isDisable()) {

                    Point2D localPosition = node.screenToLocal(positionX, positionY);

                    if (localPosition != null && node.contains(localPosition)) {
                        if (gi.isOn()) {
                            Platform.runLater(() -> node.fireEvent(
                                    new GazeEvent(GazeEvent.GAZE_MOVED, gi.getTime(), positionX, positionY)));

                            // log.info(GazeEvent.GAZE_MOVED + " : " + gi.getNode());
                        } else {

                            gi.setOn(true);
                            gi.setTime(System.currentTimeMillis());
                            Platform.runLater(() -> node.fireEvent(
                                    new GazeEvent(GazeEvent.GAZE_ENTERED, gi.getTime(), positionX, positionY)));

                            // log.info(GazeEvent.GAZE_ENTERED + " : " + gi.getNode());
                        }
                    } else {// gaze is not on the shape

                        if (gi.isOn()) {// gaze was on the shape previously

                            gi.setOn(false);
                            gi.setTime(-1);
                            Platform.runLater(() -> node.fireEvent(
                                    new GazeEvent(GazeEvent.GAZE_EXITED, gi.getTime(), positionX, positionY)));
                            // log.info(GazeEvent.GAZE_EXITED + " : " + gi.getNode());
                        } else {// gaze was not on the shape previously
                            // nothing to do

                        }

                    }
                }
            }
        }
    }`

**Comment by schwabdidier** [comment]
ok, it would be certainly better

**Comment by kuhlkrein** [comment]
I'm doing a pull request with the code. But I didn't test with all the games yet. It seems to work fine, I added a "platform.runlater" in the tobii device manager and I have the impression that it made the interaction more fluid ...  I will continue to test all the games one by one and I will then change some of the codes to add only the root of the game at the very beginning (and the rest will be done recursively). I also have to modify the remove function so that it remove the nodes recursivly
