### ISSUE TITLE
cake doesn't work in GazePlay 1.4.0

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#564]
can't select anything with eye tracker

**Comment by kuhlkrein** [comment]
Ok I will retry on monday because it was working fine for me... maybe I modified something in friday.

**Comment by schwabdidier** [comment]
It doesn't work with GazePlay 1.4.0. I didn't try with development version on windows but it works on my mac.

**Comment by kuhlkrein** [comment]
OK so it's "only" for the new 1.4.0 version but now it works ? I think it's because I changed the tobiiGazeDeviceManager.

**Comment by kuhlkrein** [comment]
Ok, I will try to see what can be the problem but it seems to work fine on my side.
