### ISSUE TITLE
Button modification ?

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#577]
I tried to created buttons with the colors of gazeplay, but I'm not sure about the result... what do you think : 

![image](https://user-images.githubusercontent.com/24478346/43253004-2ebd122c-90c4-11e8-9384-96f4cf793f1a.png)

**Comment by schwabdidier** [comment]
The constrast is not enough for the button yellow white. white should be black maybe or yellow more dark.

**Comment by kuhlkrein** [comment]
I added some shadow to keep the idea and color of the gazeplay logo
