### ISSUE TITLE
Source files of Skullhack pictures

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#588]
If I am not wrong, we don't have source files for all pictures you made @Skullhack . Is it possible to upload  them ?

**Comment by Skullhack** [comment]
Do you know what pictures are missing ? I checked order's and divisor's data folder, my pictures are here. Do they not show while playing ?

**Comment by schwabdidier** [comment]
I mean source files (to modify them if needed one day)

**Comment by Skullhack** [comment]
I don't have them anymore because I changed my harddisk, but you can modify the PNG files, I put them directly into the games data after creating them.
