### ISSUE TITLE
On Mac Os x, problem with first shoot of cream pie

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#605]
Sometimes... cream pie come from the upper right side of the screen.

**Comment by Sannaraek** [comment]
I am unable to replicate this problem on my system

**Comment by wafaahs** [comment]
I was only able to replicate the issue when I am not in fullscreen mode.. is that maybe related to the change in window size?

**Comment by schwabdidier** [comment]
no more bug
