### ISSUE TITLE
Implement several new metrics for gaze analysis

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#607]
https://imotions.com/blog/7-terms-metrics-eye-tracking/

**Comment by johzz-o2** [comment]
I am trying to implement the first point mentioned in this article : **Fixations and gaze points** .

**Comment by schwabdidier** [comment]
Cut in issues #652 #653 #654 #655 #656 #657 #658 #659 #660 #661 #662 #663
