### ISSUE TITLE
New Game: Frog Race 

### ISSUE THREAD

**Issue by Sannaraek** [schwabdidier/GazePlay#620]
I am working on a new game which would resemble a racing concept.
The screen would be split into 2.
There would be a total of 5 (or less, to be determined) players, say frogs, at the bottom of the screen. They would race to a finishing line.
On top of the screen, on the other hand, flies will be flying around randomly. 
Each target hit on the flies would move our frog further in the race.
There would be occasional faster flies that would speed up the progress of our frog drastically if obtained and offer special effects.
If our frog reaches the finishing line first, we win!
it can have several levels (easy-intermediate-difficult for instance) 
I believe this would create a sense of competition added on shooting games.

**Comment by schwabdidier** [comment]
done
