### ISSUE TITLE
Game Idea: Biboule Jump

### ISSUE THREAD

**Issue by teoblachere** [schwabdidier/GazePlay#631]
I'm going to try to make version of _Doodle Jump_ but with a biboule as the protagonist.
Doodle Jump is a classic mobile game, it's a vertical scrolling platformer, where the player has to jump on platforms to reach the highest point he can, while avoiding monsters and holes that could end his journey short and without falling off screen.
![doodle jump](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fallthingsd.com%2Ffiles%2F2011%2F09%2Fdoodle-jump-ipad.png)

**Comment by schwabdidier** [comment]
Ok, how would be done gaze interactions ?

**Comment by teoblachere** [comment]
The biboule moves towards the gaze, you should be able to gaze at a platform to land on it.
