### ISSUE TITLE
Rush Hour Main Car Not clear

### ISSUE THREAD

**Issue by wafaahs** [schwabdidier/GazePlay#646]
I noticed that it is hard to distinguish the main car that we need to bring out of the parking lot from the rest of the cars. 
At first, my suggestion was to color it with a more vibrant color than that of others. 
After going through the code, I noticed that the main car is initially set to red (which would have been a good color to distinguish) but is then overridden by a yellow taxi png image later on, with lights on top. So I am not sure it is possible to turn the main car color into red or change its color. The lights are a good indication but are a little hard to distinguish.

Another fix that I suggest, however, would be to make sure all other cars have colors that are different from yellow (no orange or similar shades for example) so that the yellow car stands out more. Because with the current implementation, we can have other yellow cars in the parking, and also the orange cars are very similar to the yellow one.

**Comment by johzz-o2** [comment]
@schwabdidier the main car is the yellow / taxi like car . So this issue can be closed because it has been resolved a few weeks back .
