### ISSUE TITLE
Games categorized

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#647]
For instance "target games" "fixation games"...

**Comment by johzz-o2** [comment]
I'll start working on this .

**Comment by schwabdidier** [comment]
How do you plan to resolve that ?

**Comment by johzz-o2** [comment]
@schwabdidier  I was thinking of creating an initial menu with game categories and then depending on which category is chosen the corresponding games appear like in the current version. What do you think ?

**Comment by schwabdidier** [comment]
done
