### ISSUE TITLE
Literacy game : 

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#651]
An image (big size image from block game) is hidden with boxes. Each one letter or one sharp (#). When the user stare (fixation) a letter, it disappears. When all letters have disappear, the reward is shown.

- options : boxes (2*2; 3*3,2*3,...)
- letter can be chosen
- letter is pronounced when it disappears

**Comment by schwabdidier** [comment]
@wafaahs  The idea is to help letter recognition (very first step for litteracy).

**Comment by wafaahs** [comment]
@schwabdidier  Okay so we will have an (n by n) grid of letters, and when the player stares at one of them, the letter sound is played?

**Comment by schwabdidier** [comment]
yes

**Comment by wafaahs** [comment]
Okay I will be working on it

**Comment by schwabdidier** [comment]
done
