### ISSUE TITLE
game play : location of targets on screen

### ISSUE THREAD

**Issue by YannRobert** [schwabdidier/GazePlay#66]
In Ninja and CreamPie, targets are always located in the top left quarter of the screen.

When a new target shows up, the gaze is already on that part of the screen, so targets can be hit accidentally as soon as they appear.

**Comment by schwabdidier** [comment]
For me, they are not always in the top left. 

Of course, if gaze is already on that part of screen, target are hit. Statistics "count" a such hit as an uncount shoot. Do you suggest something else ?

**Comment by YannRobert** [comment]
Ok, I'll check the code to understand why the location is not evenly distributed on my screen.

About statistics, I did not really paid attention to it yet.

**Comment by YannRobert** [comment]
At first, I though it was on purpose, so that the game is easier for the player.

**Comment by schwabdidier** [comment]
You were right, MaxX was only 1000 and MaxY was 2/3*500. Now it is ScreenMaxX-circle radius and 2/3*(ScreenMaxY - circle radius)

**Comment by YannRobert** [comment]
by the way, you can prefix issue number with # before in commit message, to get automatic back reference from the issue in GitHub like this 
```
fix issue #66
```

**Comment by schwabdidier** [comment]
Thank you ! I will try next bug !
