### ISSUE TITLE
Basic Math Game: Math 101

### ISSUE THREAD

**Issue by wafaahs** [schwabdidier/GazePlay#662]
I will be working on a basic math game, that can possibly be extended, depending on the need of the users. 
The idea is to teach or train kids to do basic math calculations on small numbers: Addition and subtraction. 
The game will be similar to the WhereIs games and to the Magic Card games. 

The screen will be split horizontally into two parts: 
- The upper part will show an equation (ex: 1+2)
- The lower part will show 3 possible answers on cards (ex: "3" "2" "5")

The user will choose the answer with their gaze until they find the right one. 

The range of numbers can be configured (1 to 8, 1 to 12, 1 to 20). 

An extension to this game will be to implement more complex operations such as multiplication and division and so on.  

This game is based on the game takamath01: 
http://www.takatamuser.com/mobile/fr/takamath01.html

**Comment by schwabdidier** [comment]
Yes. Interesting. Maybe is it possible to simply do it through « where is it games ? »

**Comment by wafaahs** [comment]
I considered that possibility, however I noticed that those games do not allow us to keep the questions fixed on the screen and that it would be difficult to impose that.. and I think it is important to keep the equation visible in this context because it requires more time to think and analyze the answer than just remembering a word (as is the case for other where is games). 
Also, considering that we would have half of the screen for the equation, I don't think we can put more than 3 options in the lower part, the screen would be too crowded.. 

Do you think I should still try?

**Comment by schwabdidier** [comment]
The questions are always on the bottom side of the screen. It doesn't work for you ?

see capture

<img width="1280" alt="Capture d’écran 2019-03-14 à 16 48 50" src="https://user-images.githubusercontent.com/23239584/54371091-1ba07b00-4679-11e9-84f1-ee4a723c4edb.png">

**Comment by wafaahs** [comment]
Oh yes.. but it totally disappears when not in full screen (so I guess I didn't notice it) and it's not really obvious to focus on.. 
Honestly I am not sure this is the best way to represent the game.. because the goal here is different.. it's not only gaze related, but also math related.. 
So for example I think it would be interesting to see how much time the user spends looking at the question vs how much they would spend to actually answer.. which could tell us how easy or hard this is for the kids.

**Comment by schwabdidier** [comment]
Maybe a solution is to move elements on this new game.

**Comment by wafaahs** [comment]
Yes this is exactly what I was trying to do.. combining elements from both where is it games and the Magic Card one. 
I will continue working that way.

**Comment by schwabdidier** [comment]
done with pull request #695
