### ISSUE TITLE
GitHub problem : why  sannarek doesn’t appear in statistics ?

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#670]
For instance here https://github.com/schwabdidier/GazePlay/pulse

**Comment by Sannaraek** [comment]
I think I have found the problem, my statistics now appears on insights

**Comment by schwabdidier** [comment]
What was the problem ? In order to know if it happen to someone else

**Comment by Sannaraek** [comment]
Some information like my email, my name were missing.
I think Loung has a similar problem.

**Comment by schwabdidier** [comment]
ok @Sannaraek (true, now I can even tag you !)
