### ISSUE TITLE
Biboule jump does't work with eye-tracker

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#680]
it only follows mouse.

**Comment by schwabdidier** [comment]
@teoblachere I try to see if I can make a patch.

**Comment by schwabdidier** [comment]
@teoblachere Sorry, I was unable to patch it. It won't be in this release.

**Comment by teoblachere** [comment]
I'll try to find the bug when I'm in, on Wednesday.
Too bad it's not in this release, guess it'll have to wait for the next one.

**Comment by kuhlkrein** [comment]
I'm fixing it, you just need to replace the part of the code related to event by this : 

interactionOverlay = new Rectangle(0, 0, dimensions.getWidth(), dimensions.getHeight());
        
        EventHandler<Event> movementEvent = (Event event) -> {
            if (event.getEventType() == MouseEvent.MOUSE_MOVED) {
                gazeTarget = new Point2D(((MouseEvent) event).getX(), ((MouseEvent) event).getY());
            } else if (event.getEventType() == GazeEvent.GAZE_MOVED) {
                gazeTarget = interactionOverlay.screenToLocal(  ((GazeEvent) event).getX() ,((GazeEvent) event).getY() );
            }
        };

       // interactionOverlay.addEventFilter(MouseEvent.MOUSE_MOVED, movementEvent);
        interactionOverlay.addEventFilter(GazeEvent.GAZE_MOVED, movementEvent);
        interactionOverlay.setFill(Color.TRANSPARENT);
        foregroundLayer.getChildren().add(interactionOverlay);
        
        gameContext.getGazeDeviceManager().addEventFilter(interactionOverlay);




(I commented the mouse part but you can uncomment it if you want the game to be playable by mouse too)

**Comment by kuhlkrein** [comment]
and don't forgot the 


        gameContext.getGazeDeviceManager().addEventFilter(restartButton);

after the declaration of restartButton.

btw, it's really fun to play :+1:  

(just to let you know, the "gameContext.getGazeDeviceManager().addEventFilter(Node n)" function will add the node n to the tobii listener, the fact of adding the event filter is not sufficient, you also need to call this function after having setted the event ;) )
