### ISSUE TITLE
Unable to run gazeplay after pull of current version 

### ISSUE THREAD

**Issue by Sannaraek** [schwabdidier/GazePlay#690]
I am unable to run gazeplay after doing a pull on the latest master branch

![Screenshot 2019-04-04 at 12 54 15 PM](https://user-images.githubusercontent.com/19200270/55550767-5b3b0f80-56d9-11e9-94d6-46b5990eb714.png)

**Comment by schwabdidier** [comment]
It should ok now. Can you confirm and close if yes ?

**Comment by johzz-o2** [comment]
I have the same problem as @Sannaraek , and it's not okay with the latest update either .

**Comment by schwabdidier** [comment]
I made this commit 5b8b075 . I forgot to add a picture openMemoryNumbers.jpg to the git.

**Comment by Sannaraek** [comment]
@schwabdidier Confirmed now running! Thank you!
