### ISSUE TITLE
Problem of Maven

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#71]
As yesterday version 1.0.5 was officially released as stable version, I tried to go to version 1.0.6 and since that travis doesn't work anymore. @YannRobert How to process to change number of version ?

**Comment by YannRobert** [comment]
@schwabdidier you should follow the process described in
https://github.com/schwabdidier/GazePlay/blob/master/BUILD.MD#how-to-release-the-software-for-version-tagging-in-official-scm-and-binaries-distribution

In short, the release plugin should change all of the pom files for you. It will ask you multiple questions. Most of the time it will guess the correct answer, so you just have to hit ENTER multiple times to validate.
So you really never have to edit the pom version manually. It will make the git commits too. (1 commit for the released version, and 1 commit for the next development version).

**Comment by schwabdidier** [comment]
I had to perform a release:update-versions at the end. It seems to be ok now.

**Comment by YannRobert** [comment]
Here is a little screencast, following instructions to build and release the software.

![gazeplay-maven-release-demo](https://user-images.githubusercontent.com/1653590/32682073-ed061958-c672-11e7-9de0-c8e5ee2ee9da.gif)

At the end, you should get 
* a tagged version in github.
* and binaries located in the target directory

You then just have to go to github.com, edit the release associated to the tag, and upload the binaries.

I hope this helps.

**Comment by schwabdidier** [comment]
Ok, I certainly did something wrong when I try. I will test when I go to version 1.0.7.

And when I want to go to 1.1.0 ? I should certainly write it somewhere,  but my idea is to increase 2nd number when I add games. And I think I will try soon as all other functionalities seems to work.

**Comment by schwabdidier** [comment]
Ok, I just have to write it... easy
