### ISSUE TITLE
A simple dice

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#723]
On order to permit children to play with their brothers sisters, a game which could be a simple dice throw.

**Comment by schwabdidier** [comment]
One could choose one to five dice

**Comment by teoblachere** [comment]
Sounds fun, I can try making something, should I think about making it portable into other games? Like for example, if in the future someone creates a board game and needs to throw dice, they could use my dice throw.

**Comment by schwabdidier** [comment]
Good work !
