### ISSUE TITLE
New Game : Magic Potions 

### ISSUE THREAD

**Issue by johzz-o2** [schwabdidier/GazePlay#732]
The idea is the following : 
The player will be asked to mix liquids in his disposal to create potions. The potions will be of different colors and the liquids in his disposal are only 3 (the primary colors). So to create a potion the player will have to mix the correct colors if not he will make a wrong chemical reaction and his/her lab will explode. For example creating a purple potion will require mixing red + blue liquids.

**Comment by schwabdidier** [comment]
yes, it can funny
