### ISSUE TITLE
KeyCodeProperty.java ?

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#760]
what is this class @petinhoss7 ? you add it on the 15th of march and it is at the root of the project https://github.com/schwabdidier/GazePlay/blob/master/KeyCodeProperty.java

**Comment by petinhoss7** [comment]
Hello Didier, 
I will check it and see where I used it, but I don't think I used it somewhere, I must have added it by mistake in a commit. 
Regards, 
Peter 


De: "Didier Schwab" <notifications@github.com> 
À: "schwabdidier/GazePlay" <GazePlay@noreply.github.com> 
Cc: "Peter Bardawil" <Peter.Bardawil@grenoble-inp.org>, "Mention" <mention@noreply.github.com> 
Envoyé: Samedi 1 Juin 2019 19:27:26 
Objet: [schwabdidier/GazePlay] KeyCodeProperty.java ? (#760) 



what is this class [ https://github.com/petinhoss7 | @petinhoss7 ] ? you add it on the 15th of march and it is at the root of the project [ https://github.com/schwabdidier/GazePlay/blob/master/KeyCodeProperty.java | https://github.com/schwabdidier/GazePlay/blob/master/KeyCodeProperty.java ]

**Comment by petinhoss7** [comment]
In fact, this file is useless, you can remove it or I will delete it in my next commit.

**Comment by schwabdidier** [comment]
done
