### ISSUE TITLE
Change speed Effect of the game using the keyboard 

### ISSUE THREAD

**Issue by johzz-o2** [schwabdidier/GazePlay#765]
I thought it would be a nice shortcut to increment or decrease the speed of the effect via the + / - keys. 
![speedEffect](https://user-images.githubusercontent.com/40126702/58794381-5373ea80-85f8-11e9-9a31-1a3252f0b129.png)

**Comment by schwabdidier** [comment]
fully agree :)

**Comment by schwabdidier** [comment]
resolved with pull request #789
