### ISSUE TITLE
Favorite Games

### ISSUE THREAD

**Issue by wafaahs** [schwabdidier/GazePlay#779]
A way to let the users favorite the games they like the most so that they can always see them in an easier way:

- Add a heart button on the corner of the game card to favorite them. 

- Always keep favorited games on top of the list for the user to easily reach them.

**Comment by schwabdidier** [comment]
@johzz-o2  For now, "Always keep favorited games on top of the list for the user to easily reach them." is not implanted isn't it ?

**Comment by johzz-o2** [comment]
@schwabdidier  no it isn't . I attempted at it but wasn't successful, I'll retry on Monday  :+1:

**Comment by schwabdidier** [comment]
It can’t be dynamic certainly like horizontal vertical menu in configuration that need to restart game.

**Comment by schwabdidier** [comment]
done
