### ISSUE TITLE
Space game : ship moves a lot

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#780]
On my mac, it moves fastly on the left and on the right (1cm right, 1cm left)

**Comment by schwabdidier** [comment]
@hlong205

**Comment by hlong205** [comment]
the movement of the spaceship depends on the speed of the configuration. In my computer, I set it to around 1/4 of the speed bar in my computer. I can make some adjustment to it and will test it by tomorrow when I have the eye tracker.
