### ISSUE TITLE
Legend for improving the heatmap & fixation sequence readability.

### ISSUE THREAD

**Issue by johzz-o2** [schwabdidier/GazePlay#787]
![location_probability_heat_map](https://user-images.githubusercontent.com/40126702/60001365-9f99d400-9666-11e9-946e-d2a2e18329f6.jpg)

Taking into account the feedback from the specialists of the French national association for disabled people, a way to improve readability of the metrics would be to add a _**legend**_ . Like in the example of this picture taken from wikipedia. In our case we would have to indicate the time related to each colour of the heatmap .

**Comment by schwabdidier** [comment]
Nice idea !

**Comment by johzz-o2** [comment]
In addition to that it would be nice to add a MouseListener/GazeListener to the heatMap image and display the time corresponding to the colour whenever the user hovers/gazes at the heatmap .

**Comment by schwabdidier** [comment]
Nice idea too !

**Comment by schwabdidier** [comment]
(it should be another issue)
