### ISSUE TITLE
In the Space Game , problems with the space ship

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#801]
as noticed by @johzz-o2 in #798, in the Space Game , the space ship doesn't move smoothly and also it's movement is restricted . It never extends to the width of the screen.

**Comment by johzz-o2** [comment]
@schwabdidier I think this issue is related to Windows somehow . I tried it on Ubuntu and it works fine .

**Comment by teoblachere** [comment]
It works fine on my Windows

**Comment by johzz-o2** [comment]
@teoblachere  yes , I tried again , and it looks all right . 😕

**Comment by schwabdidier** [comment]
seems ok
