### ISSUE TITLE
Problems for name of categories

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#804]
They should be the ones we introduced in this article

https://hal.archives-ouvertes.fr/hal-01804271/document

Action-Reaction Skill

Selection Skill

Memorization Skill

Certainly, we can also add a "logic" category as proposed by @wafaahs in issue #707

**Comment by johzz-o2** [comment]
I will make the modifications 👍

**Comment by schwabdidier** [comment]
done
