### ISSUE TITLE
Sound effects are sometimes played partially or not at all

### ISSUE THREAD

**Issue by teoblachere** [schwabdidier/GazePlay#809]
I don't know if it's only on my computer, but often, a sound effect is not played or only part of it is.
I've encountered this in games such as "Identify the letters", "Biboule Jump" and "Goose game", where the sound effects are short and are played one after the other rapidly.

**Comment by johzz-o2** [comment]
Also the "Bravo" sound continues playing even after we exit the game . For instance when we quit the game via the shortcut key .

**Comment by schwabdidier** [comment]
Yes, it is true, there are some little problems with sound. I was unable to resolve them previously.

**Comment by schwabdidier** [comment]
seems resolved
