### ISSUE TITLE
Setting heat map colors in configurations

### ISSUE THREAD

**Issue by teoblachere** [schwabdidier/GazePlay#812]
Allow the user to customize the heat map colors.
So if a user is colorblind, or has any vision problems, they can set the colors how ever they want them to be.
The heat map is already set up to receive any array of colors, and interpolate between them.
The user could also be allowed to modify the heat map opacity to their liking.

**Comment by teoblachere** [comment]
I'm looking into it, it seems challenging, but doable.

**Comment by schwabdidier** [comment]
Good idea

**Comment by teoblachere** [comment]
#813
