### ISSUE TITLE
Many heap space bugs with selection boxs

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#815]
items "selections games", "memorization games"...

**Comment by johzz-o2** [comment]
@schwabdidier a way to avoid the heap space errors is to renounce the dynamic filtering of the games .
I tried increasing the heap space to 2G but the problem persisted after several selections/deselections . What do you think ?

**Comment by schwabdidier** [comment]
Yes, for now, let's forget it. In the future, maybe we can have a menu with two levels ? One level for categories ("target games", "selection games",...) and then games at the lower level.

**Comment by schwabdidier** [comment]
we will change the menu
