### ISSUE TITLE
Game with animated farm

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#833]
With these images (for instance)

Background https://www.freepik.com/free-vector/farm-with-barn_1075672.htm#position=2&page=1&query=farm

animals and vehicles https://www.freepik.com/free-vector/farm-elements-design_965160.htm#position=0&page=1&query=farm

Sounds can be find here for instance http://soundbible.com

**Comment by schwabdidier** [comment]
From that skin, it can be possible to make the same for space, jungle, street...

**Comment by teoblachere** [comment]
I'm on it

**Comment by schwabdidier** [comment]
done
