### ISSUE TITLE
GazePlay works with java 1.8

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#860]
There were several modification with Java :

- There is a commercial version (done by oracle) and an open-source version (done by oracle and others like IBM) openjdk
- JavaFx is no longer in this versions and has to be separately installed
- For now, we stay at Java 1.8 (and jdk 1.8) with GazePlay

**Comment by Tohaker** [comment]
What may be the implications of including JFX11 as a Maven Dependency? Could it be redistributed with the package?

**Comment by schwabdidier** [comment]
Yes, I think so. I just didn't have time to investigate that. I check if I didn't forget to add an issue about it.

**Comment by Tohaker** [comment]
This has now been addressed in the latest PR.

**Comment by schwabdidier** [comment]
Deprecated
