### ISSUE TITLE
Warning:(46, 22) java: javafx.animation.TranslateTransitionBuilder in javafx.animation has been deprecated

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#861]
In MarqueeText.java
 `transition = TranslateTransitionBuilder.create().duration(new Duration(speed)).node(this.text)
                .interpolator(Interpolator.LINEAR).cycleCount(Animation.INDEFINITE).build();`

**Comment by Tohaker** [comment]
Fixed in latest PR
