### ISSUE TITLE
[Suggestion] Move build over to Gradle

### ISSUE THREAD

**Issue by Tohaker** [schwabdidier/GazePlay#879]
Gradle projects are simpler to read for newcomers, and are at least twice as fast to build as Maven. We can also create tasks such as release builds for better automation. 
We will also have better support for later releases on Java. 

I'll have a go at porting it over locally and see if we can solve a few problems with it.

**Comment by schwabdidier** [comment]
It is quite interesting, it is true I have never used Gradle. I propose to compare avantages of each one on this particular application.

**Comment by Tohaker** [comment]
Solved in PR #880
