### ISSUE TITLE
Add default English offline webpage.

### ISSUE THREAD

**Issue by Tohaker** [schwabdidier/GazePlay#881]
The landing page for when a user has no internet connection currently defaults to French, and the English method has no usages, plus it is written in French still. 

Found in file: `net/gazeplay/OpeningPopUp.java`

**Comment by Tohaker** [comment]
I propose the default should first query the users language settings to determine a page. 
Perhaps it's possible to implement some kind of auto-translate to reduce the amout of code written?

**Comment by schwabdidier** [comment]
It is a bug :) I wrote the function buildEnglishPage but I forgot to call it...
