### ISSUE TITLE
Travis error

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#883]
https://travis-ci.org/schwabdidier/GazePlay/builds/586103068?utm_medium=notification&utm_source=email

**Comment by Tohaker** [comment]
Oops, I know what this is. Travis can't test JavaFX because it doesn't have a display. We just need to stop tests running on the Gradle build with the `-x test` flag on the command line.

**Comment by schwabdidier** [comment]
It works !
