### ISSUE TITLE
Your photo ?

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#889]
Hello,

Next Sunday, I give a talk at the national days of Rett Syndrome about many things including Gazeplay. 

I would like to have a slide which mention that it is a joint work with you. Can you send me a photo ? :) didier.schwab at gmail

**Comment by Tohaker** [comment]
Sounds very interesting, please feel free to use the photo I have on Github

**Comment by schwabdidier** [comment]
@kuhlkrein @YannRobert @coylz what about you ?
