### ISSUE TITLE
Problem of size with animated logo

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#913]
I have a problem with the animated logo. It is too big on my screen. When I change what I called VALUE below, I can manage that. I think it is related to scree size (on my mac, it is 2560 x 1600).

Can we have a better way to manage display on screens ?

Class GazePlayAnimatedLogo
```
public static GazePlayAnimatedLogo newInstance() {
        final HBox letters = new HBox();
        //String imageType = "fixed-size";
        String imageType = "flow-size";
        for (int i = 0; i <= VALUE; i++) {
            StackPane letter = createLetterView(i, imageType);
            //
            letters.getChildren().add(letter);
        }
```

when VALUE = 3
<img width="1280" alt="Capture d’écran 2019-11-03 à 11 24 35" src="https://user-images.githubusercontent.com/23239584/68083756-086f3500-fe2d-11e9-9218-10ae0f3cae18.png">

when value = 2 (current default value)
<img width="1280" alt="Capture d’écran 2019-11-03 à 11 26 58" src="https://user-images.githubusercontent.com/23239584/68083761-1624ba80-fe2d-11e9-9ef2-9c39f6f061ae.png">

**Comment by YannRobert** [comment]
PR #915 may fix this issue.

**Comment by YannRobert** [comment]
is it fixed ?

**Comment by schwabdidier** [comment]
oh yes ! definitely !

<img width="1267" alt="Capture d’écran 2019-11-03 à 20 31 50" src="https://user-images.githubusercontent.com/23239584/68090841-0632c800-fe79-11e9-978d-017bf6164b19.png">
