### ISSUE TITLE
Make one unique setup file

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#96]
This file should install everything based on Operating System.

I want to build an installation program which will, in a nutshell :
 - make the GazePlay default directory
 - on windows : copy the dll for tobii EyeX or 4C
 - Install images especially the ones for where is the animal game and where is the color game.
 - add a shortcut on the desktop
 - (maybe) add a JVM to help people (I am not sure about that point in fact)

**Comment by schwabdidier** [comment]
I am little bit lost here.

I am unable to build a zip with images for where is the animal game and where is the color game.

I tried to modified the gameplay-dist for that purpose but I was unable. Any tips @YannRobert ?

**Comment by YannRobert** [comment]
I'll look into it tonight @schwabdidier

**Comment by schwabdidier** [comment]
I just add a look today. I was very busy this week. It is perfect @YannRobert, thank you very much. We will be able to publish a new release very soon.
